export function homePage(preflightPassed) {
 const campaignStatus=preflightPassed?'Free marketplace routes checked. Real hires and lending activity are still needed.':'Qualification paused while the second free marketplace route is checked.';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yield Proof · Testnet lending reports</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1320;color:#eaf1ff;font:16px/1.6 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:40px 24px}a{color:#85d6ff}header{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid #283a54;padding-bottom:18px}.brand{font-size:20px;font-weight:750}.badge{font-size:13px;border:1px solid #3e5970;padding:5px 12px;border-radius:30px;color:#a7e8ca}h1{font-size:clamp(32px,5vw,54px);line-height:1.1;max-width:700px;margin:44px 0 18px}h2{font-size:22px}p{max-width:750px}.muted,small{color:#b5c5da}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.box,section{background:#152239;border:1px solid #24344c;border-radius:16px;padding:22px;margin:20px 0}.grid .box{margin:0}.value{font-size:27px;font-weight:700;overflow-wrap:anywhere}.label{color:#b5c5da;font-size:14px}.status{background:#282635;border-color:#56504b}button{border:0;border-radius:8px;background:#f6c84b;color:#17181a;padding:12px 18px;font-weight:700;cursor:pointer}button.secondary{background:#243a56;color:#eaf1ff}button:disabled{opacity:.5;cursor:wait}select{padding:12px;color:inherit;background:#0c1320;border:1px solid #3b5272;border-radius:8px;max-width:100%;font:inherit}label{display:block;margin-bottom:8px}form{display:flex;gap:12px;flex-wrap:wrap;align-items:end}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}ul{padding-left:22px}.links{display:flex;gap:20px;flex-wrap:wrap}footer{border-top:1px solid #283a54;padding-top:20px;font-size:14px;margin-top:40px}.error{color:#ffb0b0}.hidden{display:none}@media(max-width:650px){.grid{grid-template-columns:1fr}header{align-items:flex-start}.value{font-size:24px}main{padding:24px 18px}}
</style></head><body><main><header><span class="brand">Yield Proof</span><span class="badge">Practice tokens · BSC testnet</span></header><h1>Understand a lending position.<br>Check the evidence.</h1><p class="muted">A useful report on Venus lending, the agent owner's position and observed interest. Try it below without connecting a wallet or paying.</p>
<div class="grid" aria-label="Lending snapshot"><div class="box"><div class="label">Quoted supply APY</div><div class="value" id="apy">Loading…</div><small>Protocol rate estimate, not income</small></div><div class="box"><div class="label">Current test position</div><div class="value" id="position">Loading…</div><small>Test BNB represented by vBNB</small></div><div class="box"><div class="label">Confirmed observed interest</div><div class="value" id="interest">Loading…</div><small id="interest-at">Computed from confirmed cashflows</small></div></div>
<p id="snapshot-status" class="muted" role="status">Reading public BSC testnet data…</p>
<section><h2>Ask for a report</h2><form id="task-form"><div><label for="task">Choose a useful question</label><select id="task"><option value="Explain the current supply APY and its assumptions">Explain the yield estimate</option><option value="Check the next supply decision and the reason to act or hold">Check the next lending decision</option><option value="Explain position growth, deposits and earned interest">Separate deposits from interest</option><option value="Audit the confirmed lending evidence">Audit the transaction evidence</option></select></div><button id="ask" type="submit">Get report</button></form><p class="muted">This preview inspects the agent owner's testnet position. It doesn't move tokens and doesn't count as a marketplace hire.</p><pre id="answer" role="status" aria-live="polite">Choose a question to see the live result.</pre><button class="secondary hidden" id="download" type="button">Save this report</button></section>
<section class="status"><h2>Campaign progress</h2><p>${campaignStatus}</p><ul><li>Identity registered: agent <b>2550</b>, BSC testnet.</li><li id="actions-count">Loading confirmed lending actions…</li><li>HelloFugu listing <a href="https://app.hellofugu.xyz/agent/97%3A2550#hire">22</a> confirmed. Completed hires remain pending.</li></ul><p>Three independent users must genuinely hire the agent. Simulation traffic doesn't satisfy that requirement.</p><div class="links"><a href="/register">Registration proof</a><a href="/operate">Owner operations</a><a href="https://github.com/SiddhantOfficial/bnb-yield-proof/blob/main/docs/user-trial-guide.md">User trial guide</a></div></section>
<footer><div class="links"><a href="/qualification">Campaign evidence</a><a href="/api/report">Raw evidence</a><a href="/.well-known/agent-card.json">Agent card</a><a href="https://github.com/SiddhantOfficial/bnb-yield-proof">Public source</a><a href="https://github.com/SiddhantOfficial/bnb-yield-proof/blob/main/docs/marketplace-preflight.md">Marketplace audit</a></div><p>Test tokens have no cash value. Quoted APY is an estimate. No guaranteed yield or campaign prize.</p></footer></main>
<script type="module">
const $=id=>document.getElementById(id);let savedReport=null;
async function load(){try{const r=await fetch('/api/report',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Report unavailable');$('apy').textContent=d.market.estimatedSupplyApyPercent===null?'Unavailable':d.market.estimatedSupplyApyPercent+'%';$('position').textContent=d.position.estimatedUnderlyingTbnb+' tBNB';const s=d.evidence.confirmedAccounting;$('interest').textContent=s?.observedInterestTbnb===null||s?.observedInterestTbnb===undefined?'Not yet verified':s.observedInterestTbnb+' tBNB';$('interest-at').textContent=s?.timestamp?'Confirmed as of '+new Date(s.timestamp).toUTCString():'Complete cashflow history required';$('snapshot-status').textContent='Observed '+new Date(d.observedAt).toUTCString()+'. Market '+(d.market.listed&&!d.market.paused?'listed and accepting supplies.':'currently unavailable for supply.')+' APY assumes 0.45-second blocks.';$('actions-count').textContent=d.actions.length+' confirmed lending actions on '+new Set(d.actions.map(x=>x.utcDay||x.utc?.slice(0,10))).size+' UTC days.';}catch(e){for(const id of ['apy','position','interest'])$(id).textContent='Unavailable';$('snapshot-status').textContent='Live data could not be loaded: '+e.message;$('snapshot-status').className='error';$('actions-count').textContent='Action history unavailable; no completion claimed.'}}
$('task-form').onsubmit=async e=>{e.preventDefault();$('ask').disabled=true;$('download').classList.add('hidden');$('answer').textContent='Checking public evidence…';try{const question=$('task').value;const r=await fetch('/a2a',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method:'message/send',params:{message:{kind:'message',role:'user',messageId:crypto.randomUUID(),parts:[{kind:'text',text:question}]}}})});const b=await r.json();if(!r.ok||b.error)throw Error(b.error?.message||'Report unavailable');const text=b.result.parts.filter(x=>x.kind==='text').map(x=>x.text).join('\\n');$('answer').textContent=text;savedReport={simulationOnly:false,previewOnly:true,qualifyingHire:false,agentId:2550,chainId:97,question,receivedAt:new Date().toISOString(),response:b.result};$('download').classList.remove('hidden');}catch(e){savedReport=null;$('answer').textContent='Report unavailable: '+e.message;}finally{$('ask').disabled=false}};
$('download').onclick=()=>{if(!savedReport)return;const url=URL.createObjectURL(new Blob([JSON.stringify(savedReport,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='yield-proof-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
load();
</script></body></html>`;
}
