import { OWNER, AGENT_ID, MARKET } from './domain.js';

const same = (a, b) => typeof a === 'string' && typeof b === 'string' && a.toLowerCase() === b.toLowerCase();
const hash = x => /^0x[0-9a-f]{64}$/i.test(x || '');
const positive = x => /^\d+$/.test(String(x)) && BigInt(x) > 0n;
function delivered(h) {
 if(!h || h.chainId !== 97 || !Number.isSafeInteger(Number(h.agentId)) || Number(h.agentId) <= 0 || h.engagement?.simulationOnly !== false || h.engagement?.http !== 200 || !h.engagement?.response || h.completion?.serviceDelivered !== true || h.completion?.settled !== true || h.hire?.status !== 'success' || !hash(h.hire.txHash) || h.completion?.settlement?.receiptStatus !== 'success' || !hash(h.completion.settlement.txHash))return false;
 const hire=Date.parse(h.hire.utc),delivery=Date.parse(h.engagement.receivedAt || h.engagement.requestedAt),settled=Date.parse(h.completion.settlement.utc);
 if(!(delivery >= hire && settled >= delivery))return false;
 if(h.marketplace === 'HelloFugu')return same(h.hire.contract,'0xfdb083371f44Cf53181350389D3217e51B431776') && same(h.completion.settlement.contract,h.hire.contract) && h.hire.event === 'Subscribed(uint256,uint256,address,address,uint256)' && positive(h.hire.amountWei) && String(h.completion.settlement.subscriptionId) === String(h.subscriptionId) && h.completion.settlement.eventTopic === '0xd9cb1e2714d65a111c0f20f060176ad657496bd47a3de04ec7c3d4ca232112ac' && h.completion.settlement.grossClaimedWei === h.hire.amountWei && delivery <= Date.parse(h.completion.periodEndsAt) && settled >= Date.parse(h.completion.periodEndsAt);
 if(h.marketplace === 'Pokter')return same(h.hire.contract,'0xa206c0517B6371C6638CD9e4a42Cc9f02A33B0DE') && h.hire.event === 'JobCreated' && h.completion.status === 'completed' && h.completion.manifestHashVerified === true && positive(h.hire.amountWei);
 return false;
}
const uniqueReceipts = entries => {const seen=new Set();return entries.filter(h=>{const key=h.hire.txHash.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});};

// Summarize reviewed records. This is not an independent chain audit or organizer approval.
export function qualificationSummary({ identity, preflight, hires, evidence, availability, liveOwner, now = new Date().toISOString() }) {
 const registered = identity.chainId === 97 && String(identity.agentId) === AGENT_ID && same(identity.owner, OWNER) && hash(identity.registrationTx) && same(liveOwner, OWNER);
 const afterRegistration = x => Number.isFinite(Date.parse(x)) && Date.parse(x) >= Date.parse(identity.registrationUtc) && Date.parse(x) <= Date.parse(now) && Date.parse(x) <= Date.parse('2026-11-05T12:00:00Z');
 const listing = registered && preflight.listing?.status === 'confirmed' && preflight.listing.chainId === 97 && String(preflight.listing.agentId) === AGENT_ID && same(preflight.listing.owner, OWNER) && same(preflight.listing.agentWallet, OWNER);
 const outbound = uniqueReceipts((hires.outbound || []).filter(h => delivered(h) && String(Number(h.agentId)) !== AGENT_ID && h.direction === 'outbound' && same(h.campaignWallet, OWNER) && afterRegistration(h.hire.utc) && afterRegistration(h.completion.settlement.utc)));
 const identities = new Set(outbound.map(h => `${h.chainId}:${Number(h.agentId)}`));
 const marketplaces = new Set(outbound.map(h => h.marketplace));
 const inbound = uniqueReceipts((hires.inbound || []).filter(h => delivered(h) && h.direction === 'inbound' && String(Number(h.agentId)) === AGENT_ID && h.independence?.verified === true && /^0x[0-9a-f]{40}$/i.test(h.hirer || '') && !same(h.hirer, OWNER) && afterRegistration(h.hire.utc) && afterRegistration(h.completion.settlement.utc)));
 const independentWallets = new Set(inbound.map(h => h.hirer.toLowerCase()));
 const ledgerMatches = evidence.chainId === 97 && same(evidence.owner, OWNER) && same(evidence.market, MARKET) && evidence.ledgerComplete === true;
 const actions = ledgerMatches ? (evidence.actions || []).filter(a => a.verified === true && a.chainId === 97 && same(a.owner, OWNER) && same(a.market, MARKET) && positive(a.amountWei) && ['supply','redeem'].includes(a.type) && hash(a.txHash) && afterRegistration(a.utc || a.timestamp)) : [];
 const uniqueActions = [...new Map(actions.map(a => [a.txHash.toLowerCase(), a])).values()];
 const days = [...new Set(uniqueActions.map(a => new Date(a.utc || a.timestamp).toISOString().slice(0,10)))].sort();
 const latestProbe = availability.observations?.at(-1) || null;
 const gates = [
  { label:'Registered identity owned by campaign wallet', ready:!!registered, detail:`Agent ${AGENT_ID}, chain 97. Campaign form submission is owner-reported.` },
  { label:'Marketplace listing for the same owned agent', ready:!!listing, detail:'HelloFugu listing 22; published receipt. Continued listing availability needs review.' },
  { label:'Three distinct outbound agents across two marketplaces', ready:identities.size >= 3 && marketplaces.size >= 2, detail:`${identities.size}/3 distinct delivered and settled agents; ${marketplaces.size}/2 marketplaces.` },
  { label:'Three independent users completed hires', ready:independentWallets.size >= 3, detail:`${independentWallets.size}/3 wallets with reviewed independence and completion records.` },
  { label:'Five lending actions across three UTC dates', ready:uniqueActions.length >= 5 && days.length >= 3, detail:`${uniqueActions.length}/5 recorded lending actions; ${days.length}/3 UTC dates. Ledger ${ledgerMatches ? 'reconciled' : 'incomplete'}.` },
  { label:'Public endpoint answers live probes', ready:latestProbe?.ok === true && Date.parse(now)-Date.parse(latestProbe.at) >= 0 && Date.parse(now)-Date.parse(latestProbe.at) < 6*60*60*1000, detail:latestProbe ? `Latest recorded probe: ${latestProbe.at}; continued availability required.` : 'No recorded probe.' }
 ];
 return { agentId:AGENT_ID,chainId:97,owner:OWNER,generatedAt:now,registrationUtc:identity.registrationUtc,deadlineUtc:'2026-11-05T12:00:00Z',recordedGatesReady:gates.every(g => g.ready),campaignQualificationConfirmed:false,status:'Qualification pending BNB Chain review',gates,counts:{outboundAgents:identities.size,outboundMarketplaces:marketplaces.size,independentInboundWallets:independentWallets.size,lendingActions:uniqueActions.length,lendingUtcDays:days},outbound,inbound,actions:uniqueActions,latestProbe,limitations:['Counts summarize public reviewed records, not a fresh replay of every transaction.','Distinct wallets alone do not establish independent users.','Simulation and failed transactions are excluded. Test tokens have no cash value.','No live first-100 rank, guaranteed prize or profit is claimed.'],sources:{repository:'https://github.com/SiddhantOfficial/bnb-yield-proof',rules:'https://www.bnbchain.org/en/hackathons/smart-money-era-set-and-earn',evidence:'https://github.com/SiddhantOfficial/bnb-yield-proof/blob/main/docs/submission.md'}};
}

export function qualificationPage() {
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yield Proof · Evidence</title><style>body{background:#0b1320;color:#eaf1ff;font:17px/1.6 system-ui;margin:0}main{max-width:1000px;margin:48px auto;padding:24px}a{color:#77d4ff}section{background:#17243a;padding:24px;border-radius:16px;margin:24px 0}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #40516c}code{overflow-wrap:anywhere}h1,h2{line-height:1.2}.pending{color:#ffd36d}.ready{color:#80e0b3}button{padding:12px;font:inherit}small{color:#bdcce0}</style><main><a href="/">← Yield Proof</a><h1>Campaign evidence</h1><p>Agent 2550 · BSC Testnet · Test tokens only</p><section><h2 id="status">Loading reviewed records…</h2><p id="updated"></p><table><thead><tr><th>Requirement</th><th>Recorded status</th></tr></thead><tbody id="gates"></tbody></table><p>Registration is already owner-reported as submitted. This page is an evidence index; it does not submit a new application or confirm a reward.</p></section><section><h2>Confirmed hires and lending actions</h2><ul id="receipts"></ul><a href="/api/qualification">Full JSON evidence summary</a> · <a href="https://github.com/SiddhantOfficial/bnb-yield-proof/blob/main/docs/submission.md">Reviewer checklist</a> · <a href="/api/report">Live Venus report</a></section><section><h2>Try a useful testnet task</h2><p>Ask Yield Proof to explain the Venus rate, distinguish deposits from observed interest, or audit a published lending transaction.</p><p><a href="https://app.hellofugu.xyz/agent/97%3A2550#hire">Hire agent 2550 on HelloFugu</a> with one two-minute period using your own wallet and independently obtained free test BNB. Request a report from the <a href="/">public app</a>, then preserve the subscription, delivered report and escrow release records.</p><p><a href="https://github.com/SiddhantOfficial/bnb-yield-proof/blob/main/docs/user-trial-guide.md">Independent trial guide and example tasks</a></p></section><small>No guaranteed first-100 placement or profits. Onchain records and endpoint checks remain subject to BNB Chain review. <a href="https://www.bnbchain.org/en/hackathons/smart-money-era-set-and-earn">Official rules</a></small></main><script>
fetch('/api/qualification').then(async r=>{if(!r.ok)throw Error('Evidence currently unavailable');return r.json()}).then(d=>{document.getElementById('status').textContent=d.status;document.getElementById('updated').textContent='Read at '+d.generatedAt+' · deadline 5 November 2026, 12:00 UTC';for(const g of d.gates){const row=document.createElement('tr');const name=document.createElement('td');name.textContent=g.label;const state=document.createElement('td');state.className=g.ready?'ready':'pending';state.textContent=(g.ready?'Recorded — ':'Pending — ')+g.detail;row.append(name,state);document.getElementById('gates').append(row)}for(const h of d.outbound){for(const [label,url] of [[h.marketplace+' agent '+h.agentId+' hire',h.hire.explorer],[h.marketplace+' settlement',h.completion.settlement.explorer]])add(label,url)}for(const a of d.actions)add('Venus '+a.type+' · '+(a.utc||a.timestamp),'https://testnet.bscscan.com/tx/'+a.txHash);function add(label,url){if(!url||!url.startsWith('https://testnet.bscscan.com/tx/'))return;const li=document.createElement('li');const a=document.createElement('a');a.textContent=label;a.href=url;li.append(a);document.getElementById('receipts').append(li)}}).catch(e=>{document.getElementById('status').textContent='Evidence unavailable';document.getElementById('updated').textContent=e.message});
</script></html>`;
}
